#!/usr/bin/env bash
#
# Bootstrap the 3-node meshdb cluster with a small TPC-H-shaped dataset and run a walkthrough of
# the classic TPC-H query shapes against it. The point, as with demo.sh, is that a client talks to
# ANY node in plain SQL and never knows the data is sharded across all three — here with a realistic
# star-schema workload instead of a single toy table.
#
# It reuses the SAME cluster as demo.sh (docker-compose.yml). Data is generated by tpch_data.py
# (deterministic, no dbgen) — see that file for the schema and the scaled-down sizing.
#
# Requires: docker (with the compose plugin), curl, python3.
set -euo pipefail
cd "$(dirname "$0")"

PORTS=(8081 8082 8083)   # host ports → node1/node2/node3 HTTP gateways

run() { # <host-port> <sql>  → prints the JSON response
  local body
  body=$(python3 -c 'import json,sys; print(json.dumps({"sql": sys.argv[1]}))' "$2")
  curl -s -X POST "http://127.0.0.1:$1/v1/run" -H 'content-type: application/json' -d "$body"
}

# Pretty-print a /v1/run result as an aligned table (falls back to raw JSON on an error/no rows).
show() { # <host-port> <sql>
  run "$1" "$2" | python3 -c '
import json,sys
d=json.load(sys.stdin)
if "error" in d:
    print("  ERROR:", d["error"]); sys.exit()
cols=d.get("columns"); rows=d.get("rows")
if cols is None:
    print("  ", d); sys.exit()
w=[len(c) for c in cols]
for r in rows:
    for i,v in enumerate(r): w[i]=max(w[i], len("" if v is None else str(v)))
def line(vals): print("   " + "  ".join(("" if v is None else str(v)).ljust(w[i]) for i,v in enumerate(vals)))
line(cols); print("   " + "  ".join("-"*x for x in w))
for r in rows: line(r)
plural = "s" if len(rows) != 1 else ""
print("   (%d row%s)" % (len(rows), plural))
'
}

echo "==> building the image (once) and starting 3 nodes"
docker compose build
docker compose up -d

echo "==> waiting for the gateways to answer"
for _ in $(seq 1 90); do
  curl -sf "http://127.0.0.1:${PORTS[0]}/v1/health" >/dev/null 2>&1 && break
  sleep 1
done

echo "==> waiting for the cluster to elect a leader and place shards"
sleep 6

# Idempotent: if the dataset is already loaded (e.g. a re-run to reach the console), skip the load
# and go straight to the walkthrough. `count(*)` on a missing table comes back as a null row.
loaded=$(run "${PORTS[0]}" "SELECT count(*) AS n FROM lineitem" \
  | python3 -c 'import json,sys
try:
    v=json.load(sys.stdin).get("rows",[[None]])[0][0]
    print(v if isinstance(v,int) else 0)
except Exception:
    print(0)')
if [ "${loaded:-0}" -gt 0 ]; then
  echo "==> dataset already loaded ($loaded lineitem rows); skipping the load"
else
  echo "==> generating a small TPC-H dataset"
  mapfile -t STMTS < <(python3 tpch_data.py)
  echo "    ${#STMTS[@]} statements (region, nation, customer, orders, lineitem)"

  echo "==> loading it, rotating which node we write to (node 1, 2, 3, 1, …)"
  echo "    every INSERT is auto-routed to whichever node owns the row's shard, wherever we send it"
  i=0
  for stmt in "${STMTS[@]}"; do
    resp=$(run "${PORTS[$(( i % 3 ))]}" "$stmt")
    case "$resp" in
      *'"error"'*) echo "    load failed on: $stmt"; echo "    $resp"; exit 1;;
    esac
    i=$(( i + 1 ))
    (( i % 40 == 0 )) && printf '    …%d/%d\n' "$i" "${#STMTS[@]}"
  done
  echo "    done: $i statements loaded"
fi

echo
echo "════════════════════════════════════════════════════════════════════════════"
echo " TPC-H walkthrough — each query hits a DIFFERENT node, all sharded underneath"
echo "════════════════════════════════════════════════════════════════════════════"

echo
echo "# Row counts, each a cross-shard count gathered from all three nodes (asked of node 1):"
for tbl in lineitem orders customer nation region; do
  n=$(run "${PORTS[0]}" "SELECT count(*) AS n FROM $tbl" \
      | python3 -c 'import json,sys; print(json.load(sys.stdin)["rows"][0][0])')
  printf '   %-10s %s\n' "$tbl" "$n"
done

echo
echo "# Q1 — Pricing Summary Report (asked of node 2)."
echo "#   A GROUP BY over the whole lineitem table: each node aggregates its own shards, the"
echo "#   coordinator two-phase-merges the partials. Money is integer cents, so the merged answer"
echo "#   is EXACTLY a single-node one."
show "${PORTS[1]}" "SELECT l_returnflag, l_linestatus,
    sum(l_quantity)            AS sum_qty,
    sum(l_extendedprice_cents) AS sum_base_price,
    sum(l_disc_price_cents)    AS sum_disc_price,
    count(*)                   AS count_order
  FROM lineitem
  WHERE l_shipdate <= '1998-09-01'
  GROUP BY l_returnflag, l_linestatus
  ORDER BY l_returnflag, l_linestatus"

echo
echo "# Q6 — Forecasting Revenue Change (asked of node 3)."
echo "#   A filtered sum across every shard: a WHERE on shipdate/discount/quantity, one number back."
show "${PORTS[2]}" "SELECT sum(l_disc_price_cents) AS revenue, count(*) AS qualifying_lines
  FROM lineitem
  WHERE l_shipdate >= '1994-01-01' AND l_shipdate < '1995-01-01'
    AND l_discount_pct BETWEEN 2 AND 6 AND l_quantity < 24"

echo
echo "# Orders by status — a grouped aggregate on a different table (asked of node 1):"
show "${PORTS[0]}" "SELECT o_orderstatus, count(*) AS orders, sum(o_totalprice_cents) AS revenue
  FROM orders GROUP BY o_orderstatus ORDER BY o_orderstatus"

echo
echo "# Customers per region — a 3-way JOIN (customer⋈nation⋈region), asked of node 2."
echo "#   These tables shard by different keys, so the join is NOT co-located; meshdb still returns"
echo "#   the correct answer by materialising it centrally."
show "${PORTS[1]}" "SELECT r.r_name AS region, count(*) AS customers
  FROM customer c JOIN nation n ON c.c_nationkey = n.n_nationkey
                  JOIN region r ON n.n_regionkey = r.r_regionkey
  GROUP BY r.r_name ORDER BY r.r_name"

echo
echo "# A point lookup for one order (asked of node 3) — routed to the single shard that holds it:"
show "${PORTS[2]}" "SELECT o_orderkey, o_custkey, o_orderstatus, o_totalprice_cents
  FROM orders WHERE o_orderkey = 42"

echo
echo "cluster is live with the TPC-H dataset. Poke it directly against any node, e.g.:"
echo "  curl -s localhost:8082/v1/run -d '{\"sql\":\"SELECT count(*) FROM lineitem\"}'"

# Hand off to the web console so the dataset is immediately browsable in the UI. console.sh sees
# the cluster is already up, launches the console, pre-registers the 3 nodes as a connection, and
# blocks until Ctrl-C (which stops the console; the cluster keeps running). Set TPCH_NO_CONSOLE=1
# to finish here instead — e.g. for a non-interactive run.
if [ "${TPCH_NO_CONSOLE:-0}" = "1" ]; then
  echo "Tear it down with:  docker compose -f \"$(pwd)/docker-compose.yml\" down"
  exit 0
fi
echo
echo "==> starting the web console (set TPCH_NO_CONSOLE=1 to skip)"
exec ./console.sh
